FROM ubuntu:20.04

LABEL maintainer="gavrilenko40"
RUN  mkdir -p  /etc/tempest && mkdir -p /var/log/tempest && mkdir /tempest

# if you are behind proxy , uncomment this variables and set your proxy here)
#ENV http_proxy=
#ENV https_proxy=
#ENV no_proxy=


ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
  apt-get install -y  git \
  gcc \
  sshpass \
  python3-setuptools \
  python3-virtualenv \
  netcat \
  netbase \
  openssh-server \
  python3-minimal \
  python3-setuptools \
  python3-pip \
  python3-dev \
  python3-dateutil \
  ca-certificates \
  openstack-pkg-tools \
  apache2 \
  libmysqlclient-dev \
  gcc \
  g++ \
  libffi-dev \
  python3-openstackclient \
  libssl-dev --no-install-recommends && \
  apt-get clean

#install it with pip
RUN  pip install tempest

# also you can clone and install it from https://github.com/openstack/tempest.git
# RUN git clone https://github.com/openstack/tempest.git && cd tempest/
# RUN pip install . 
# just uncomment this block , and comment #"RUN  pip install tempest"

WORKDIR /tempest
RUN tempest init

COPY init.sh /tempest/init.sh
RUN chmod +x /tempest/init.sh
